# Site settings
title: Hugh Rawlinson
email: hugh@codeoclock.net
description: "A student of music computing, a developer of software, an experiencer of things"
baseurl: ""
url: "http://www.hughrawlinson.me"
twitter_username: hughrawlinson
github_username:  hughrawlinson

# Build settings
markdown: kramdown
permalink: pretty
